# Generated by Django 4.2.11 on 2025-07-31 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_reactivationrequest_kycreviewlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual income in USD for credit limit evaluation",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
