image: python:3.10-slim

pipelines:
  branches:
    staging:
      - step:
          name: Install Dependencies and Run Tests (Staging)
          caches:
            - pip
          script:
            - apt-get update && apt-get install -y --no-install-recommends libpq-dev libffi-dev
            - pip install --upgrade pip
            - pip install -r requirements.txt
            - python manage.py test
          services:
            - postgres
            - redis

      - step:
          name: Build and Push Docker Image (Staging)
          caches:
            - docker
          script:
            - docker build -t credify_django_app:staging .
            - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            - docker tag credify_django_app:staging $DOCKERHUB_USERNAME/credify_django_app:staging-$BITBUCKET_COMMIT
            - docker push $DOCKERHUB_USERNAME/credify_django_app:staging-$BITBUCKET_COMMIT
          services:
            - docker

    main:
      - step:
          name: Install Dependencies and Run Tests (Production)
          caches:
            - pip
          script:
            - apt-get update && apt-get install -y --no-install-recommends libpq-dev libffi-dev
            - pip install --upgrade pip
            - pip install -r requirements.txt
            - python manage.py test
          services:
            - postgres
            - redis

      - step:
          name: Build and Push Docker Image (Production)
          caches:
            - docker
          script:
            - docker build -t credify_django_app:latest .
            - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            - docker tag credify_django_app:latest $DOCKERHUB_USERNAME/credify_django_app:$BITBUCKET_COMMIT
            - docker push $DOCKERHUB_USERNAME/credify_django_app:$BITBUCKET_COMMIT
          services:
            - docker

definitions:
  services:
    docker:
      memory: 1024
    postgres:
      image: postgres:14
      memory: 2048  
      environment:
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    redis:
      image: redis:7
      memory: 512

options:
  docker: true
