# Generated by Django 4.2.11 on 2026-04-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('credit_limit_increase', 'Credit Limit Increase'), ('credit_limit_decrease', 'Credit Limit Decrease'), ('card_upgrade', 'Card Upgrade'), ('card_downgrade', 'Card Downgrade'), ('card_replacement', 'Card Replacement'), ('card_cancellation', 'Card Cancellation'), ('single_use_card_request', 'Single-Use Card Request'), ('card_unfreeze', 'Card Unfreeze Request'), ('transaction_dispute', 'Transaction Dispute'), ('refund_request', 'Refund Request'), ('transaction_clarification', 'Transaction Clarification'), ('failed_transaction', 'Failed Transaction Report'), ('kyc_re_submission', 'KYC Re-submission Request'), ('account_reactivation', 'Account Reactivation'), ('profile_update_request', 'Profile Update Request'), ('account_closure', 'Account Closure'), ('subscription_cancellation', 'Subscription Cancellation'), ('subscription_upgrade', 'Subscription Upgrade'), ('billing_dispute', 'Billing Dispute'), ('fee_waiver', 'Fee Waiver Request'), ('suspected_fraud', 'Suspected Fraud Report'), ('pin_reset', 'PIN / Security Reset'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('in_process', 'In Process'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='raised', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('user_comment', models.TextField(blank=True)),
                ('document', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reraises', to='enquiry.userrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
