# Generated by Django 4.2.11 on 2026-04-22 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnquiryStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='admin_comment',
            new_name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='is_viewed_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='sla_breached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['user'], name='enquiry_use_user_id_7452bb_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['status'], name='enquiry_use_status_c21394_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['assigned_to'], name='enquiry_use_assigne_c0d6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['request_type'], name='enquiry_use_request_f88310_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['sla_breached'], name='enquiry_use_sla_bre_ca7fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['created_at'], name='enquiry_use_created_13cd97_idx'),
        ),
        migrations.AddField(
            model_name='enquirystatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirystatuslog',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enquiry.userrequest'),
        ),
        migrations.AddField(
            model_name='enquirycomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirycomment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enquiry.userrequest'),
        ),
    ]
