# Generated by Django 4.2.11 on 2025-07-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_alter_creditcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="cvv",
            field=models.CharField(max_length=128),
        ),
    ]
