# Generated by Django 4.2.11 on 2025-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_alter_creditcard_cvv"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creditcard",
            old_name="Card_Type",
            new_name="card_type",
        ),
    ]
