# Generated by Django 4.2.11 on 2025-07-30 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "default_credit_limit",
                    models.DecimalField(decimal_places=2, default=575.6, max_digits=10),
                ),
                ("expiry_years", models.IntegerField(default=3)),
                (
                    "transaction_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("requires_admin_approval", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CardRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_single_use", models.BooleanField(default=False)),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("occupation", models.CharField(max_length=100)),
                ("intended_use", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cards.cardtype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=64, unique=True)),
                ("cvv", models.CharField(max_length=32)),
                ("expiry_date", models.DateField()),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "available_credit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("frozen", "Frozen"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("is_single_use", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Card_Type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="cards.cardtype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["card_number"], name="cards_credi_card_nu_d64078_idx"
                    ),
                    models.Index(
                        fields=["user"], name="cards_credi_user_id_b763b0_idx"
                    ),
                ],
            },
        ),
    ]
