# Generated by Django 4.2.11 on 2025-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_number",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
