# Generated by Django 4.2.11 on 2025-08-07 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0005_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
