# Generated by Django 4.2.11 on 2025-09-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_creditcard_card_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='effective_card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effective_cards', to='cards.cardtype'),
        ),
    ]
